### ISSUE TITLE
3D segmentation?

### ISSUE THREAD

**Issue by lajart** [instanseg/instanseg#13]
Hello, 

I'm pleasantly surprised to see how well Instanseg is working with data, even when my signal is very heterogenous. Has the model been tested for 3D segmentation, or do you suggest doing MIPs or just running the model on the Z stack, and then using an IoU operation similar to CellPose? I could whip up a loop to do it, but just asking in case I can save time.

**Comment by ThibautGoldsborough** [comment]
Hi,

Glad you had a positive experience with InstanSeg. I'm afraid we haven't done any work to make it compatible for 3D segmentation so far - although I wouldn't be surprised if there was an elegant way to do it. We're unlikely to support 3D in the very near future though.

**Comment by rhornb** [comment]
Dear @ThibautGoldsborough, 

thank you for this amazing tool, InstanSeg works like a charm for my data! 

Like @lajart, I would be also interested in a 3D implementation of InstanSeg. 

I was playing around with multiple ideas on how to create pseudo3D segmentations. So far, I have tested:
- IoU merging of xy views as suggested by @lajart unfortunately does not work for me due to dense segmentations that results in long merged labels in zx. 
- Parsing of xy views into the [uSegment3D](https://github.com/DanuserLab/u-segment3D) library, particularly the `uSegment3D.aggregate_2D_to_3D_segmentation_indirect_method()` function to leverage probabilities and gradients to merge slices into consensus 3D segmentation. This approach probably requires some further parameter tuning, but so far didn't outperform IoU merging in my hands.

Due to the anisotropy of my data (z:1, y:0.33, x:0.33), I haven't looked into running InstanSeg along the orthoviews.

Another hacky approach I wanted to test is feeding the 2D UNet (boundary) predictions into e.g. PlantSeg to use a graph-partitioning approach to extract 3D labels. However, I have not managed to retrieve the predictions of InstanSeg yet. Is there a way to return the (boundary) predictions of InstanSeg next to the labels? 

Many thanks in advance, 
Ruth

**Comment by ThibautGoldsborough** [comment]
Hi @rhornb,

I'm glad you're finding InstanSeg useful. Thank you for reporting your findings using IoU and uSegment3D. 

InstanSeg doesn't use boundary predictions, it uses a novel embedding based approach described in our [preprint](https://arxiv.org/abs/2408.15954). To recover the embeddings from a torchscript you can run:
`instanseg = torch.jit.load(path_to_torchscript_model)
embeddings = instanseg.fcn(torch.randn(1, 3, 256, 256).to(device))` (replace torch.randn with your image tensor).

The last channel of `embeddings` will be a predicted distance map.
