### ISSUE TITLE
Unconsistency in segmentation masks

### ISSUE THREAD

**Issue by koopa31** [instanseg/instanseg#46]
Hi,
While training a model, I figured out several times there can be a non consitent behaviour.
In the upper right image, we can see there's an ROI inside an ROI. Methodologically, I don't know the method enough to understand what can make that happen. Have you ever noticed that?
![output_epoch_65](https://github.com/user-attachments/assets/f9caa163-2836-4d38-9117-ea3bbc5aa57a)

Thank you!

**Comment by koopa31** [comment]
By the way, I noticed another issue in the prediction, probably due to tiling. Sometimes, cell masks are cut off. It seems to be because it's been segmented on the left tile and not on the right one (see yellow big cell below):
![image](https://github.com/user-attachments/assets/b138ba9e-6504-4ade-964c-79149e79d470)

**Comment by ThibautGoldsborough** [comment]
(1) Not sure I'd say it's an inconsistency, but yes you can have that sort of artefact in the early stages of training. It's not a bug, it's just a lack of training.  [InstanSeg](https://arxiv.org/abs/2408.15954) does not use a watershed or flow tracking algorithm so can indeed predict disconnected objects.  I will say your objects are quite big, roughly 64 pixels in diameter, that's roughly the field of view of our default unet which is why it's struggling a little. You can increase the depth of the unet using --layers "[32,64,128,256,512]" during training if you wish.

(2) Again your objects are really big and go beyond the default "crop" around the objects (see Figure 1 of our preprint). You can increase this at inference using window_size = 64 (the crop is 2* window_size, default is 32) to the eval_small_image or eval_medium_image or the forward pass of the torchscript. You avoid these issues if run at a reasonable pixel size (0.25 - 0.5 microns per pixel)

**Comment by koopa31** [comment]
Thanks for your answer. I've been training for 250 epochs (default value) with around 10,000 nuclei. In your experience do you think it's enough? Actually, the loss and the F1 score are stable quite early (around 50 epochs) and it seems after that there's no real interest in keeping training.
Which UNet depth have you chosen for your datasets?

**Comment by ThibautGoldsborough** [comment]
In our paper and public models we use the default depth. But the objects are smaller than the nuclei in your image. (Curious, is this a DSB 2018 image?)

**Comment by koopa31** [comment]
It's not a public dataset image. It's an image I acquired myself into a zebrafish.
